INSERT ALL
INTO FIRE_LGA VALUES (
SELECT * FROM DUAL;

INSERT ALL
INTO FIRE_EVENT VALUES (
SELECT * FROM DUAL;

INSERT ALL
INTO LGA VALUES (
SELECT * FROM DUAL;

INSERT ALL
INTO PROPERTY VALUES (
SELECT * FROM DUAL;

INSERT ALL
INTO PROPERTY_TYPE VALUES (
SELECT * FROM DUAL;

INSERT ALL
INTO OWNER VALUES (
SELECT * FROM DUAL;

INSERT ALL
INTO OWNER_TYPE VALUES (
SELECT * FROM DUAL;

INSERT ALL
INTO BUILDING VALUES (
SELECT * FROM DUAL;

INSERT ALL
INTO DAMAGE_COST VALUES (
SELECT * FROM DUAL;

INSERT ALL
INTO ASSESSOR VALUES (
SELECT * FROM DUAL;

INSERT ALL
INTO INSURANCE VALUES (
SELECT * FROM DUAL;

INSERT ALL
INTO ASSESSOR_HISTORY VALUES (
SELECT * FROM DUAL;

COMMIT;

